/**
 * SF Demo World Schema - defines a space-faring civilization simulation.
 * Three factions compete for control of star systems through diplomacy, trade, and combat.
 */

import type { WorldSchema } from '@event-horizon/types';

export const sfSchema: WorldSchema = {
  id: 'sf-cosmos',
  name: 'Cosmic Frontier',
  version: '0.1.0',
  description:
    'A space opera simulation where three factions vie for dominance across the stars through diplomacy, trade, espionage, and fleet warfare.',

  components: [
    {
      id: 'faction-info',
      name: 'Faction Info',
      description: 'Core faction data',
      fields: [
        { name: 'ideology', type: 'string', description: 'Core governing ideology' },
        { name: 'government', type: 'string', description: 'Form of government' },
        { name: 'homeSystemId', type: 'string', description: 'Home star system' },
        { name: 'color', type: 'string', description: 'Faction display color' },
      ],
    },
    {
      id: 'character-info',
      name: 'Character Info',
      description: 'Character biographical data',
      fields: [
        { name: 'species', type: 'string', description: 'Species/race' },
        { name: 'role', type: 'string', description: 'Role or rank' },
        { name: 'factionId', type: 'string', description: 'Affiliated faction' },
        { name: 'backstory', type: 'string', description: 'Character background' },
        { name: 'portrait', type: 'string', description: 'Portrait image key' },
      ],
    },
    {
      id: 'star-system',
      name: 'Star System',
      description: 'Star system properties',
      fields: [
        { name: 'starType', type: 'string', description: 'Type of star (G, K, M, etc.)' },
        { name: 'planets', type: 'number', description: 'Number of planets' },
        { name: 'controllerId', type: 'string', description: 'Controlling faction ID' },
        { name: 'contested', type: 'boolean', defaultValue: false },
        { name: 'coordinates', type: 'record', description: '{ x, y } map position' },
      ],
    },
    {
      id: 'fleet',
      name: 'Fleet',
      description: 'Military fleet composition',
      fields: [
        { name: 'ships', type: 'number', description: 'Number of ships' },
        { name: 'fleetType', type: 'string', description: 'patrol | strike | defense | expedition' },
        { name: 'commanderId', type: 'string', description: 'Fleet commander entity ID' },
        { name: 'factionId', type: 'string', description: 'Owning faction' },
      ],
    },
    {
      id: 'station',
      name: 'Station',
      description: 'Space station or outpost',
      fields: [
        { name: 'stationType', type: 'string', description: 'trade | military | research | diplomatic' },
        { name: 'capacity', type: 'number', description: 'Operational capacity' },
        { name: 'ownerId', type: 'string', description: 'Owning faction' },
      ],
    },
    {
      id: 'trade-route',
      name: 'Trade Route',
      description: 'Trade route between two locations',
      fields: [
        { name: 'fromSystemId', type: 'string' },
        { name: 'toSystemId', type: 'string' },
        { name: 'goods', type: 'string[]', description: 'Types of goods traded' },
        { name: 'volume', type: 'number', description: 'Trade volume per turn' },
      ],
    },
  ],

  entityTypes: [
    {
      id: 'faction',
      name: 'Faction',
      description: 'A major political faction',
      requiredComponents: ['faction-info'],
      optionalComponents: [],
      defaultTags: ['faction', 'major-power'],
    },
    {
      id: 'character',
      name: 'Character',
      description: 'A person in the galaxy',
      requiredComponents: ['character-info'],
      optionalComponents: [],
      defaultTags: ['character'],
      locatable: true,
    },
    {
      id: 'system',
      name: 'Star System',
      description: 'A star system with planets',
      requiredComponents: ['star-system'],
      optionalComponents: ['station'],
      defaultTags: ['location', 'system'],
    },
    {
      id: 'fleet',
      name: 'Fleet',
      description: 'A military fleet',
      requiredComponents: ['fleet'],
      optionalComponents: [],
      defaultTags: ['military', 'fleet'],
      locatable: true,
    },
  ],

  stats: [
    // Faction stats
    {
      id: 'military-power',
      name: 'Military Power',
      category: 'faction',
      min: 0,
      max: 1000,
      defaultValue: 100,
      applicableTo: ['faction'],
    },
    {
      id: 'economic-power',
      name: 'Economic Power',
      category: 'faction',
      min: 0,
      max: 1000,
      defaultValue: 100,
      applicableTo: ['faction'],
    },
    {
      id: 'tech-level',
      name: 'Technology Level',
      category: 'faction',
      min: 1,
      max: 10,
      defaultValue: 3,
      applicableTo: ['faction'],
    },
    {
      id: 'influence',
      name: 'Influence',
      category: 'faction',
      min: 0,
      max: 500,
      defaultValue: 50,
      applicableTo: ['faction'],
    },
    {
      id: 'stability',
      name: 'Internal Stability',
      category: 'faction',
      min: 0,
      max: 100,
      defaultValue: 70,
      decayPerTurn: -1,
      applicableTo: ['faction'],
    },
    // Character stats
    {
      id: 'loyalty',
      name: 'Loyalty',
      category: 'character',
      min: 0,
      max: 100,
      defaultValue: 50,
      applicableTo: ['character'],
    },
    {
      id: 'competence',
      name: 'Competence',
      category: 'character',
      min: 0,
      max: 100,
      defaultValue: 50,
      applicableTo: ['character'],
    },
    {
      id: 'ambition',
      name: 'Ambition',
      category: 'character',
      min: 0,
      max: 100,
      defaultValue: 50,
      applicableTo: ['character'],
    },
    // Fleet stats
    {
      id: 'fleet-morale',
      name: 'Fleet Morale',
      category: 'military',
      min: 0,
      max: 100,
      defaultValue: 75,
      decayPerTurn: -2,
      applicableTo: ['fleet'],
    },
    {
      id: 'fleet-strength',
      name: 'Fleet Strength',
      category: 'military',
      min: 0,
      max: 500,
      defaultValue: 100,
      applicableTo: ['fleet'],
    },
    // System stats
    {
      id: 'population',
      name: 'Population',
      category: 'system',
      min: 0,
      max: 10000,
      defaultValue: 100,
      applicableTo: ['system'],
    },
    {
      id: 'resources',
      name: 'Resources',
      category: 'system',
      min: 0,
      max: 1000,
      defaultValue: 50,
      applicableTo: ['system'],
    },
    {
      id: 'defense-level',
      name: 'Defense Level',
      category: 'system',
      min: 0,
      max: 100,
      defaultValue: 20,
      applicableTo: ['system'],
    },
  ],

  relationTypes: [
    {
      id: 'diplomatic',
      name: 'Diplomatic Relations',
      description: 'Political relationship between factions',
      directed: false,
      minWeight: -100,
      maxWeight: 100,
      defaultWeight: 0,
      decayPerTurn: -1,
      allowedPairs: [['faction', 'faction']],
    },
    {
      id: 'trade',
      name: 'Trade Relations',
      description: 'Economic trade relationship',
      directed: false,
      minWeight: 0,
      maxWeight: 100,
      defaultWeight: 0,
      allowedPairs: [['faction', 'faction']],
    },
    {
      id: 'loyalty-to',
      name: 'Loyalty',
      description: "A character's loyalty to a faction",
      directed: true,
      minWeight: -100,
      maxWeight: 100,
      defaultWeight: 50,
      allowedPairs: [['character', 'faction']],
    },
    {
      id: 'personal',
      name: 'Personal Relationship',
      description: 'Personal feelings between characters',
      directed: true,
      minWeight: -100,
      maxWeight: 100,
      defaultWeight: 0,
      decayPerTurn: -2,
      allowedPairs: [['character', 'character']],
    },
    {
      id: 'command',
      name: 'Command',
      description: 'Military command relationship',
      directed: true,
      minWeight: 0,
      maxWeight: 100,
      defaultWeight: 50,
      allowedPairs: [['character', 'fleet']],
    },
  ],

  actionTypes: [
    {
      id: 'negotiate',
      name: 'Negotiate',
      description: 'Attempt diplomatic negotiation',
      performerTypes: ['character'],
      targetTypes: ['character'],
      allowedPhases: ['player-action', 'npc-action'],
      params: [
        { name: 'topic', type: 'string', options: ['alliance', 'trade', 'ceasefire', 'threat'] },
      ],
    },
    {
      id: 'move-fleet',
      name: 'Move Fleet',
      description: 'Move a fleet to a new system',
      performerTypes: ['fleet'],
      targetTypes: ['system'],
      allowedPhases: ['player-action', 'npc-action'],
    },
    {
      id: 'attack',
      name: 'Attack',
      description: 'Attack a fleet or system',
      performerTypes: ['fleet'],
      targetTypes: ['fleet', 'system'],
      allowedPhases: ['player-action', 'npc-action'],
      cooldown: 1,
    },
    {
      id: 'trade',
      name: 'Establish Trade',
      description: 'Establish or boost a trade route',
      performerTypes: ['faction'],
      targetTypes: ['faction'],
      allowedPhases: ['player-action', 'npc-action'],
      params: [{ name: 'investment', type: 'number', min: 10, max: 100 }],
    },
    {
      id: 'research',
      name: 'Research',
      description: 'Invest in technology research',
      performerTypes: ['faction'],
      allowedPhases: ['player-action', 'npc-action'],
      params: [{ name: 'investment', type: 'number', min: 10, max: 100 }],
    },
    {
      id: 'espionage',
      name: 'Espionage',
      description: 'Conduct espionage against another faction',
      performerTypes: ['character'],
      targetTypes: ['faction'],
      allowedPhases: ['player-action', 'npc-action'],
      cooldown: 2,
    },
    {
      id: 'rally',
      name: 'Rally',
      description: 'Rally support to improve stability or morale',
      performerTypes: ['character'],
      targetTypes: ['faction', 'fleet'],
      allowedPhases: ['player-action', 'npc-action'],
    },
    {
      id: 'build-fleet',
      name: 'Build Fleet',
      description: 'Commission a new fleet',
      performerTypes: ['faction'],
      targetTypes: ['system'],
      allowedPhases: ['player-action', 'npc-action'],
      params: [
        { name: 'size', type: 'number', min: 10, max: 100 },
        { name: 'fleetType', type: 'string', options: ['patrol', 'strike', 'defense', 'expedition'] },
      ],
      cooldown: 3,
    },
  ],

  phases: [
    { id: 'player-action', name: 'Player Action', type: 'player-action', order: 0 },
    { id: 'npc-action', name: 'NPC Action', type: 'npc-action', order: 1 },
    { id: 'event-resolution', name: 'Event Resolution', type: 'event-resolution', order: 2 },
    { id: 'world-update', name: 'World Update', type: 'world-update', order: 3 },
  ],

  config: {
    aiMode: 'assist',
    timeUnit: 'cycle',
    turnLabel: 'Galactic Cycle',
    activeModules: ['diplomacy', 'military', 'trade', 'espionage', 'narrative'],
    rngSeed: 42,
  },
};
