/**
 * 스타크래프트 데모 월드 스키마 - 코프룰루 구역 전쟁 시뮬레이션.
 * 테란, 프로토스, 저그 세 종족이 은하의 패권을 다툰다.
 */

import type { WorldSchema } from '@event-horizon/types';

export const sfSchema: WorldSchema = {
  id: 'sc-koprulu',
  name: '코프룰루 전쟁',
  version: '0.1.0',
  description:
    '테란, 프로토스, 저그 세 종족이 코프룰루 구역의 패권을 놓고 외교, 전투, 정신 에너지를 통해 맞서는 전쟁 시뮬레이션.',

  components: [
    {
      id: 'faction-info',
      name: '세력 정보',
      description: '핵심 세력 데이터',
      fields: [
        { name: 'ideology', type: 'string', description: '핵심 이념' },
        { name: 'government', type: 'string', description: '통치 체제' },
        { name: 'homeSystemId', type: 'string', description: '본거지 성계' },
        { name: 'color', type: 'string', description: '세력 표시 색상' },
      ],
    },
    {
      id: 'character-info',
      name: '캐릭터 정보',
      description: '캐릭터 전기 데이터',
      fields: [
        { name: 'species', type: 'string', description: '종족' },
        { name: 'role', type: 'string', description: '직위 또는 역할' },
        { name: 'factionId', type: 'string', description: '소속 세력' },
        { name: 'backstory', type: 'string', description: '캐릭터 배경 이야기' },
        { name: 'portrait', type: 'string', description: '초상화 이미지 키' },
      ],
    },
    {
      id: 'star-system',
      name: '성계',
      description: '성계 속성',
      fields: [
        { name: 'starType', type: 'string', description: '항성 유형' },
        { name: 'planets', type: 'number', description: '행성 수' },
        { name: 'controllerId', type: 'string', description: '지배 세력 ID' },
        { name: 'contested', type: 'boolean', defaultValue: false },
        { name: 'coordinates', type: 'record', description: '{ x, y } 맵 좌표' },
      ],
    },
    {
      id: 'fleet',
      name: '군단',
      description: '군사 병력 편성',
      fields: [
        { name: 'ships', type: 'number', description: '병력 수' },
        { name: 'fleetType', type: 'string', description: '공격 | 방어 | 정찰 | 원정' },
        { name: 'commanderId', type: 'string', description: '지휘관 엔티티 ID' },
        { name: 'factionId', type: 'string', description: '소속 세력' },
      ],
    },
    {
      id: 'station',
      name: '기지',
      description: '행성 기지 또는 전초기지',
      fields: [
        { name: 'stationType', type: 'string', description: '사령부 | 군사 | 연구 | 외교' },
        { name: 'capacity', type: 'number', description: '운영 용량' },
        { name: 'ownerId', type: 'string', description: '소유 세력' },
      ],
    },
    {
      id: 'trade-route',
      name: '보급로',
      description: '두 성계 간의 보급로',
      fields: [
        { name: 'fromSystemId', type: 'string' },
        { name: 'toSystemId', type: 'string' },
        { name: 'goods', type: 'string[]', description: '보급 물자 종류' },
        { name: 'volume', type: 'number', description: '턴당 보급량' },
      ],
    },
  ],

  entityTypes: [
    {
      id: 'faction',
      name: '세력',
      description: '주요 종족 세력',
      requiredComponents: ['faction-info'],
      optionalComponents: [],
      defaultTags: ['faction', 'major-power'],
    },
    {
      id: 'character',
      name: '캐릭터',
      description: '코프룰루 구역의 인물',
      requiredComponents: ['character-info'],
      optionalComponents: [],
      defaultTags: ['character'],
      locatable: true,
    },
    {
      id: 'system',
      name: '성계',
      description: '행성이 있는 항성계',
      requiredComponents: ['star-system'],
      optionalComponents: ['station'],
      defaultTags: ['location', 'system'],
    },
    {
      id: 'fleet',
      name: '군단',
      description: '군사 병력',
      requiredComponents: ['fleet'],
      optionalComponents: [],
      defaultTags: ['military', 'fleet'],
      locatable: true,
    },
  ],

  stats: [
    // 세력 능력치
    {
      id: 'military-power',
      name: '군사력',
      category: 'faction',
      min: 0,
      max: 1000,
      defaultValue: 100,
      applicableTo: ['faction'],
    },
    {
      id: 'economic-power',
      name: '자원 채굴력',
      category: 'faction',
      min: 0,
      max: 1000,
      defaultValue: 100,
      applicableTo: ['faction'],
    },
    {
      id: 'tech-level',
      name: '기술 수준',
      category: 'faction',
      min: 1,
      max: 10,
      defaultValue: 3,
      applicableTo: ['faction'],
    },
    {
      id: 'influence',
      name: '영향력',
      category: 'faction',
      min: 0,
      max: 500,
      defaultValue: 50,
      applicableTo: ['faction'],
    },
    {
      id: 'stability',
      name: '내부 결속력',
      category: 'faction',
      min: 0,
      max: 100,
      defaultValue: 70,
      decayPerTurn: -1,
      applicableTo: ['faction'],
    },
    // 캐릭터 능력치
    {
      id: 'loyalty',
      name: '충성도',
      category: 'character',
      min: 0,
      max: 100,
      defaultValue: 50,
      applicableTo: ['character'],
    },
    {
      id: 'competence',
      name: '역량',
      category: 'character',
      min: 0,
      max: 100,
      defaultValue: 50,
      applicableTo: ['character'],
    },
    {
      id: 'ambition',
      name: '야망',
      category: 'character',
      min: 0,
      max: 100,
      defaultValue: 50,
      applicableTo: ['character'],
    },
    {
      id: 'psionic-power',
      name: '사이오닉 능력',
      category: 'character',
      min: 0,
      max: 100,
      defaultValue: 0,
      applicableTo: ['character'],
    },
    // 군단 능력치
    {
      id: 'fleet-morale',
      name: '군단 사기',
      category: 'military',
      min: 0,
      max: 100,
      defaultValue: 75,
      decayPerTurn: -2,
      applicableTo: ['fleet'],
    },
    {
      id: 'fleet-strength',
      name: '군단 전투력',
      category: 'military',
      min: 0,
      max: 500,
      defaultValue: 100,
      applicableTo: ['fleet'],
    },
    // 성계 능력치
    {
      id: 'population',
      name: '인구',
      category: 'system',
      min: 0,
      max: 10000,
      defaultValue: 100,
      applicableTo: ['system'],
    },
    {
      id: 'resources',
      name: '미네랄/가스',
      category: 'system',
      min: 0,
      max: 1000,
      defaultValue: 50,
      applicableTo: ['system'],
    },
    {
      id: 'defense-level',
      name: '방어 수준',
      category: 'system',
      min: 0,
      max: 100,
      defaultValue: 20,
      applicableTo: ['system'],
    },
  ],

  relationTypes: [
    {
      id: 'diplomatic',
      name: '외교 관계',
      description: '세력 간 정치적 관계',
      directed: false,
      minWeight: -100,
      maxWeight: 100,
      defaultWeight: 0,
      decayPerTurn: -1,
      allowedPairs: [['faction', 'faction']],
    },
    {
      id: 'trade',
      name: '보급 관계',
      description: '자원 교류 관계',
      directed: false,
      minWeight: 0,
      maxWeight: 100,
      defaultWeight: 0,
      allowedPairs: [['faction', 'faction']],
    },
    {
      id: 'loyalty-to',
      name: '충성',
      description: '캐릭터의 세력에 대한 충성도',
      directed: true,
      minWeight: -100,
      maxWeight: 100,
      defaultWeight: 50,
      allowedPairs: [['character', 'faction']],
    },
    {
      id: 'personal',
      name: '개인적 관계',
      description: '캐릭터 간의 개인적 감정',
      directed: true,
      minWeight: -100,
      maxWeight: 100,
      defaultWeight: 0,
      decayPerTurn: -2,
      allowedPairs: [['character', 'character']],
    },
    {
      id: 'command',
      name: '지휘',
      description: '군사 지휘 관계',
      directed: true,
      minWeight: 0,
      maxWeight: 100,
      defaultWeight: 50,
      allowedPairs: [['character', 'fleet']],
    },
  ],

  actionTypes: [
    {
      id: 'contact',
      name: '접촉 시도',
      description: '처음 만나는 인물에게 접촉을 시도한다',
      performerTypes: ['character'],
      targetTypes: ['character'],
      allowedPhases: ['player-action', 'npc-action'],
    },
    {
      id: 'negotiate',
      name: '협상',
      description: '외교 협상 시도',
      performerTypes: ['character'],
      targetTypes: ['character'],
      allowedPhases: ['player-action', 'npc-action'],
      params: [
        { name: 'topic', type: 'string', options: ['alliance', 'trade', 'ceasefire', 'threat'] },
      ],
    },
    {
      id: 'move-fleet',
      name: '군단 이동',
      description: '군단을 새로운 성계로 이동',
      performerTypes: ['fleet'],
      targetTypes: ['system'],
      allowedPhases: ['player-action', 'npc-action'],
    },
    {
      id: 'attack',
      name: '공격',
      description: '적 군단 또는 성계를 공격',
      performerTypes: ['fleet'],
      targetTypes: ['fleet', 'system'],
      allowedPhases: ['player-action', 'npc-action'],
      cooldown: 1,
    },
    {
      id: 'trade',
      name: '자원 교역',
      description: '보급로를 개설하거나 강화',
      performerTypes: ['faction'],
      targetTypes: ['faction'],
      allowedPhases: ['player-action', 'npc-action'],
      params: [{ name: 'investment', type: 'number', min: 10, max: 100 }],
    },
    {
      id: 'research',
      name: '연구',
      description: '기술 연구에 투자',
      performerTypes: ['faction'],
      allowedPhases: ['player-action', 'npc-action'],
      params: [{ name: 'investment', type: 'number', min: 10, max: 100 }],
    },
    {
      id: 'espionage',
      name: '첩보',
      description: '다른 세력에 대한 첩보 활동',
      performerTypes: ['character'],
      targetTypes: ['faction'],
      allowedPhases: ['player-action', 'npc-action'],
      cooldown: 2,
    },
    {
      id: 'rally',
      name: '결집',
      description: '결속력 또는 사기를 높이기 위한 지지 결집',
      performerTypes: ['character'],
      targetTypes: ['faction', 'fleet'],
      allowedPhases: ['player-action', 'npc-action'],
    },
    {
      id: 'build-fleet',
      name: '병력 생산',
      description: '새로운 군단 편성 명령',
      performerTypes: ['faction'],
      targetTypes: ['system'],
      allowedPhases: ['player-action', 'npc-action'],
      params: [
        { name: 'size', type: 'number', min: 10, max: 100 },
        { name: 'fleetType', type: 'string', options: ['patrol', 'strike', 'defense', 'expedition'] },
      ],
      cooldown: 3,
    },
  ],

  phases: [
    { id: 'player-action', name: '플레이어 행동', type: 'player-action', order: 0 },
    { id: 'npc-action', name: 'NPC 행동', type: 'npc-action', order: 1 },
    { id: 'event-resolution', name: '이벤트 처리', type: 'event-resolution', order: 2 },
    { id: 'world-update', name: '세계 갱신', type: 'world-update', order: 3 },
  ],

  config: {
    aiMode: 'assist',
    timeUnit: 'cycle',
    turnLabel: '작전 주기',
    activeModules: ['diplomacy', 'military', 'trade', 'espionage', 'narrative'],
    rngSeed: 42,
  },
};
